config/routes.rb
Rails.application.routes.draw do
  get '/enfermeros/listado/:id', to: "enfermeros#baja", as: "baja"
  get '/pacientes/:id', to: "main#alta", as: "main_alta"
  get 'estadisticas/mostrar'
 
 ## get 'estadisticas/seleccionar', to: "estadisticas#seleccionar", as: "seleccionar"
  get 'enfermeros/listado', to: "enfermeros#listado", as: "listadoenfermero"
  patch 'turno/:id', to: "turnos#turno", as: "turno"  ## para guardar la nota
  patch '/aplicadasinturnoform', to: "comprobante#aplicadasinturnoform", as: "sinturno" 
  patch '/crearturnofiebreamarilla/:id', to: "turnos#crearturnofiebreamarilla", as: "crearturnofiebreamarilla"
  patch '/crearturnogripe/:id', to: "turnos#crearturnogripe", as: "crearturnogripe"
  patch '/crearturnocovid2/:id', to: "turnos#crearturnocovid2", as: "crearturnocovid2"
  patch '/crearturnocovid1/:id', to: "turnos#crearturnocovid1", as: "crearturnocovid1"
  get 'comprobante/index/:id', to: "comprobante#index", as: "comprobante_index"
  get '/crearcomprobante/:id', to: "comprobante#crearcomprobante", as: "crearcomprobante"
  get '/historialdeturnos', to: "turnos#historialdeturnos", as: "historialdeturnos"
   get '/historialdeturnospaciente/:id', to: "turnos#historialdeturnospaciente", as: "historialdeturnospaciente"
   get '/aplicadasinturno', to: "turnos#aplicadasinturno", as: "aplicadasinturno"
  get '/noaplicada/:id', to: "turnos#noaplicada", as: "noaplicada"
  get '/noasistencia/:id', to: "turnos#noasistencia", as: "noasistencia"
  get '/asistencia/:id', to: "turnos#asistencia", as: "asistencia"
  get 'turnos/listado', to: "turnos#listado", as: "ver_lista_turnos"
  get 'vacunatorios/ver_contacto', to: "vacunatorios#ver_contacto", as:"ver_contacto"
  devise_for :users, controllers:{registrations: 'users/registrations' }
  get "/verdatos", to: "main#ver", as:"verdatos"
  get "/verlistadoturnos", to: "main#verlistadoturnos", as:"verlistadoturnos"
  get "/verdetalleturno/:id", to: "main#verdetalleturno", as:"verdetalleturno"
  get "/verhistoria/:id", to: "main#verhistoria", as:"verhistoria"
  get "/covid1", to: "main#turnoscovid1", as:"turnoscovid1"
  get "/covid2", to: "main#turnoscovid2", as:"turnoscovid2"
  get "/fiebreamarilla", to: "main#turnosfiebreamarilla", as:"turnosfiebreamarilla"
  get "/gripe", to: "main#turnosgripe", as:"turnosgripe"
  get "/pacientes", to: "main#pacientes", as:"pacientes"
  get "/obtenerturno/:id" , to: "main#obtenerturno", as:"obtenerturno"
  get "/cancelarturno/:id" , to: "main#cancelarturno", as:"cancelarturno"
  get "/cancelarturnocovid1/:id" , to: "main#cancelarturnocovid1", as:"cancelarturnocovid1"
  get "/cancelarturnocovid2/:id" , to: "main#cancelarturnocovid2", as:"cancelarturnocovid2"
  get "/buscar", to: "main#search", as:"buscar"
  get "/buscarturnos", to: "turnos#searchturnos", as:"searchturnos"
  get "/buscarenfermero", to: "main#searchenfermero", as:"buscarenfermero"
  get "/verdatospaciente/:id", to: "main#verdatospaciente", as:"verdatospaciente"
  get "/verinformacionenfermero/:id", to: "enfermeros#verinformacionenfermero", as:"verinformacionenfermero"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   get "/enfermero", to: "main#pantallaenfermero", as:"pantallaenfermero"
   get "/admin", to: "main#pantallaadmin", as:"pantallaadmin"
   get 'vacunatorios/edit', to: 'vacunatorios#edit', as: 'edit_vacunatorio'
   patch 'vacunatorios/ver_contacto', to: 'vacunatorios#update'
  get "/home", to: "main#home", as:"home"
  root 'main#home'
end

app/models/vacunatorio.rb
class Vacunatorio < ApplicationRecord
   has_many :turnos
   has_many :comprobantes
end

app/controllers/vacunatorios_controller.rb
class VacunatoriosController < ApplicationController
  def ver_contacto
    @v = Vacunatorio.all
  end

  def edit
    @vacunatorio = Vacunatorio.find(params[:id])
    render :edit
  end

  def update
    @vac = Vacunatorio.find(params[:id])
    if @vac.update(params.require(:vacunatorio).permit(:email, :telefono))
      flash[:success] = "vacunatorio successfully updated!"
      redirect_to vacunatorios_ver_contacto_path, notice: "El vacunatorio se ha modificado"
    else
      flash.now[:error] = "vacunatorio update failed"
      render :edit
    end
  end

end

app/helpers/vacunatorios_helper.rb
module VacunatoriosHelper
end

app/views/vacunatorios/edit.html.erb
<!DOCTYPE html> 
<html>
<h1> Editar Datos de Contacto de Vacunatorio: <%= @vacunatorio.nombre %> </h1>

<%= form_with model: @vacunatorio, url: ver_contacto_path(:id => @vacunatorio.id), method: :patch, local: true do |f| %>


  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true , autocomplete: "email", required: true %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br />
    <%= f.number_field :telefono, autofocus: true , autocomplete: "teléfono", required: true %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Modificar Datos"%>
  </div>

 <% end %>
<br>

<%= link_to "Atrás", ver_contacto_path %>
</html>

app/views/vacunatorios/ver_contacto.html.erb
<!DOCTYPE html> 
<html>
<h1> Informacón de contacto Vacunassist</h1>
<table class = "table">
            <th>Nombre</th>
            <th>Lugar</th>
            <th>Email</th>
            <th>Telefono</th>
    <tbody>
    <% @v.each do |vac| %>
        <tr>
            <td>
                <% if vac.nombre == "Vacunatorio1" %>
                     Vacunatorio 1
                 <% elsif vac.nombre == "Vacunatorio2" %>
                           Vacunatorio 2
                 <% elsif vac.nombre == "Vacunatorio3" %>
                           Vacunatorio 3   
                 <% end %>
            </td>
            <td><%= vac.lugar %></td>
            <td><%= vac.email %></td>
            <td><%= vac.telefono %></td>
            <% if (current_user.rol == 3) %>
                <td>    
                    <button style="background-color:yellow">
                       <%= link_to "Modificar Datos de Contacto", edit_vacunatorio_path(:id => vac.id), class: 'btn btn-info btn-sm' %>
                    </button>
                </td>
            <% end %>
            
        </tr>
        
    <% end %>
    </tbody>
</table>

<%= link_to "Atrás", pantallaadmin_path %>
</html>